theme: jekyll-theme-cayman
title: The vusaverse
description: A GitHub Pages site for showcasing the vusaverse.

# Enable GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation Configuration
navigation:
  - title: Home
    url: /

  - title: About
    url: /about.html

  - title: Projects
    url: /projects.html

# Build Configuration
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

