project:
  type: website
  output-dir: docs

website:
  title: "vusaverse"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - packages.qmd
      - faq.qmd
      - projects.qmd
      - resources.qmd
      - blog.qmd
      - styleguides.qmd
    right:
      - icon: github
        href: https://github.com/vusaverse

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

