---
title: "VU Analytics"
---

VU Analytics is a VU data facility that analyses
education and student data in order to improve student intake,
progression and graduation in all phases of education.

VU Analytics is committed to using data to
support policy making, student guidance and scientific research into
academic success as effectively as possible. We call this data-informed
policy. We provide the VU with insights into student intake, progression
and graduation and thus contribute to the quality of education at the
VU.

VU Analytics investigates VU study data. This study data is created during the paths students take within the VU 'garden'.

-   Part of it is about the origin of students and what they did
    'before the gate': their previous education in the Netherlands or
    abroad, how they oriented themselves at the VU, which study choices they
    made. This includes data from Studielink, orientation data, data from
    the study choice trajectory, the introduction and the language
    proficiency test.

-   The next part is about what they do in the garden: where the VU
    career of students starts, what choices students make about their routes
    within and between programmes, their study results and academic
    success. VU Analytics largely receives this data from the student
    administration via VUdata.

-   Finally, it is about how our students fare after they leave the
    garden with a diploma: a follow-up study or their labour market success.

All these data are traces left behind in the garden. The team
combines study data to create an enriched dataset. We use the study data
in our dataset to understand our students better, to improve the
quality of education, and to study student intake, progression and
graduation.

On their path, students may come across many things
that are beautiful or could be improved. Attractive places to talk to a
lecturer or study advisor, interesting paths and flowers, but also
fallen trees or small rivers that are difficult to cross without help.
VU policy officers and programme managers turn to VU Analytics for good
advice on routes to be recommended. Together, they discuss possible
barriers. Under the watchful eye of the privacy officer, the team
investigates relevant data and provides specific advice that can be used
by colleagues and, ultimately, by students. Through all these
investigations, the team gets a good picture of the entire VU, which
helps with general issues for the VU as a whole. 

To achieve this,
Team VU Analytics has contact with a broad network of policy staff and
members of education management. VU Analytics regularly participates in
various educational consultations within the VU. We also proactively
organise a sounding board group to ensure that the initiatives and
services of VU Analytics are as closely aligned as possible with the
wishes and needs of the organisation. The sounding board group consists
of representatives from the various bodies and target groups.

We can be reached for questions about data for educational policy or scientific research at: [VU-analytics\@vu.nl](mailto:VU-analytics@vu.nl).
